version: "3.9"
services:
  api:
    build: .
    container_name: feedback-api
    restart: always
    ports:
      - "5174:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_ACCESS_KEY_ID=AKIAUQ4L3RGNWDA4DGPM
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_DEFAULT_REGION=us-east-1

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: feedback-frontend
    depends_on:
      - api
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:5174
